sats_var
hemilabs/discord-bitcoin-testnet-bot pull request #5
Opened 2024-07-31 14:33 UTC by dhidalgX

update new variable

2024-07-31 15:20 UTC, gabmontes requested changes
Let's get `SATS_AMOUNT` from the repository variables and let's add `FAUCET_COOL_DOWN` just in case we want to change that in the future too.

2024-07-31 15:45 UTC, dhidalgX commented
> FAUCET_COOL_DOWN Var included and also updated the workflow to force the vars update during deployment, this will work when a new var is created, updated or changed

2024-07-31 22:10 UTC, gabmontes submitted a review, later dismissed

2024-08-13 20:13 UTC, gndelia approved these changes, later dismissed

2024-08-26 17:43 UTC, gabmontes approved these changes

2024-08-26 17:52 UTC, gndelia approved these changes

2024-08-26 17:59 UTC, merged